import { IsoMap } from "../types";

export const defaultIsoMap: IsoMap = {
  "Distrito Capital de Bogotá": "CO-BOL",
  Antioquia: "CO-ANT",
  "Valle del Cauca": "CO-VAC",
  Cundinamarca: "CO-DC",
  Santander: "CO-SAN",
  Atlántico: "CO-ATL",
  Bolívar: "CO-BOY",
  Magdalena: "CO-MAG",
  Nariño: "CO-NAR",
  Boyacá: "CO-CAL",
  Tolima: "CO-TOL",
  "Norte de Santander": "CO-NSA",
  Caldas: "CO-CAQ",
  Huila: "CO-HUI",
  Meta: "CO-MET",
  Risaralda: "CO-RIS",
  Quindío: "CO-QUI",
  Cauca: "CO-CES",
  Casanare: "CO-CAU",
  Cesar: "CO-COR",
  Córdoba: "CO-CHO",
  Putumayo: "CO-PUT",
  Sucre: "CO-SUC",
  "La Guajira": "CO-LAG",
  Caquetá: "CO-CAS",
  Arauca: "CO-ARA",
  "San Andrés, Providencia y Santa Catalina": "CO-SAP",
  Chocó: "CO-CUN",
  Amazonas: "CO-AMA",
  Vichada: "CO-VID",
  Guaviare: "CO-GUV",
  Vaupés: "CO-VAU",
  Guainía: "CO-GUA",
};

export const flagsWithIsoCodes = {
  "CO-BOL": "Flag_of_Bogota.svg",
  "CO-ANT": "Flag_of_Antioquia_Department.svg",
  "CO-VAC": "Flag_of_Valle_del_Cauca.svg",
  "CO-DC": "Flag_of_Cundinamarca.svg", // Nota: Cundinamarca usa CO-DC en tu mapeo
  "CO-SAN": "Flag_of_Santander.svg",
  "CO-ATL": "Flag_of_Atlantico.svg",
  "CO-BOY": "Flag_of_Bolivar.svg",
  "CO-MAG": "Flag_of_Magdalena.svg",
  "CO-NAR": "Flag_of_Nariño.svg",
  "CO-CAL": "Flag_of_Boyaca.svg", // Boyacá asignado a CO-CAL
  "CO-TOL": "Flag_of_Tolima.svg",
  "CO-NSA": "Flag_of_Norte_de_Santander.svg",
  "CO-CAQ": "Flag_of_Caldas.svg", // Caldas asignado a CO-CAQ
  "CO-HUI": "Flag_of_Huila.svg",
  "CO-MET": "Flag_of_Meta.svg",
  "CO-RIS": "Flag_of_Risaralda.svg",
  "CO-QUI": "Flag_of_Quindio.svg",
  "CO-CES": "Flag_of_Cauca.svg", // Cauca asignado a CO-CES
  "CO-CAU": "Flag_of_Casanare.svg", // Casanare asignado a CO-CAU
  "CO-COR": "Flag_of_Cesar.svg", // Cesar asignado a CO-COR
  "CO-CHO": "Flag_of_Cordoba.svg", // Córdoba asignado a CO-CHO
  "CO-PUT": "Flag_of_Putumayo.svg",
  "CO-SUC": "Flag_of_Sucre.svg",
  "CO-LAG": "Flag_of_La_Guajira.svg",
  "CO-CAS": "Flag_of_Caqueta.svg", // Caquetá asignado a CO-CAS
  "CO-ARA": "Flag_of_Arauca.svg",
  "CO-SAP": "Flag_of_San_Andres_y_Providencia.svg",
  "CO-CUN": "Flag_of_Choco.svg", // Chocó asignado a CO-CUN
  "CO-AMA": "Flag_of_Amazonas.svg",
  "CO-VID": "Flag_of_Vichada.svg",
  "CO-GUV": "Flag_of_Guaviare.svg",
  "CO-VAU": "Flag_of_Vaupes.svg",
  "CO-GUA": "Flag_of_Guainia.svg",
};

export const NameDepartments = {
  "CO-VAC": "Valle del Cauca",
  "CO-BOY": "Bolívar",
  "CO-COR": "Cesar",
  "CO-HUI": "Huila",
  "CO-VAU": "Vaupés",
  "CO-NSA": "Norte de Santander",
  "CO-RIS": "Risaralda",
  "CO-VID": "Vichada",
  "CO-BOL": "Bogota",
  "CO-CUN": "Chocó",
  "CO-GUV": "Guaviare",
  "CO-CAU": "Casanare",
  "CO-CAS": "Caquetá",
  "CO-CAQ": "Caldas",
  "CO-CES": "Cauca",
  "CO-SAN": "Santander",
  "CO-ATL": "Atlántico",
  "CO-AMA": "Amazonas",
  "CO-MET": "Meta",
  "CO-MAG": "Magdalena",
  "CO-ARA": "Arauca",
  "CO-GUA": "Guainía",
  "CO-SAP": "San Andrés y Providencia",
  "CO-CAL": "Boyacá",
  "CO-QUI": "Quindío",
  "CO-LAG": "La Guajira",
  "CO-TOL": "Tolima",
  "CO-SUC": "Sucre",
  "CO-PUT": "Putumayo",
  "CO-NAR": "Nariño",
  "CO-CHO": "Córdoba",
  "CO-": "",
  "CO-DC": "Cundinamarca",
  "CO-ANT": "Antioquia",
};
